services:
  hz:
    image: hazelcast/hazelcast:5.3.6
    networks:
      - hazelcast-network
    environment:
      - HZ_CLUSTERNAME=q
  hz1:
    image: hazelcast/hazelcast:5.3.6
    networks:
      - hazelcast-network
    environment:
      - HZ_CLUSTERNAME=hello-world

  hz2:
    image: hazelcast/hazelcast:5.3.6
    networks:
      - hazelcast-network
    environment:
      - HZ_CLUSTERNAME=hello-world

  hz3:
    image: hazelcast/hazelcast:5.3.6
    networks:
      - hazelcast-network
    environment:
      - HZ_CLUSTERNAME=hello-world

  facade:
    environment:
      - ADDR=hz
      - PORT=3000
    build:
      context: ./facade
      target: final
    networks:
      - hazelcast-network
    ports:
      - 3000:3000

  logger-1:
    environment:
      - ADDR=hz1
      - PORT=3001
    networks:
      - hazelcast-network
    build:
      context: ./logging
      target: final
    ports:
      - 3001:3001

  logger-2:
    environment:
      - ADDR=hz2
      - PORT=5000
    networks:
      - hazelcast-network
    build:
      context: ./logging
      target: final
    ports:
      - 5000:5000

  logger-3:
    environment:
      - ADDR=hz3
      - PORT=7000
    networks:
      - hazelcast-network
    build:
      context: ./logging
      target: final
    ports:
      - 7000:7000

  message-1:
    environment:
      - ADDR=hz
      - PORT=5001
    build:
      context: ./message
      target: final
    networks:
      - hazelcast-network
    ports:
      - 5001:5001

  message-2:
    environment:
      - ADDR=hz
      - PORT=5002
    build:
      context: ./message
      target: final
    networks:
      - hazelcast-network
    ports:
      - 5002:5002

  message-3:
    environment:
      - ADDR=hz
      - PORT=5003
    build:
      context: ./message
      target: final
    networks:
      - hazelcast-network
    ports:
      - 5003:5003

networks:
  hazelcast-network:
    external: true
